# Generated by Django 4.2.4 on 2023-09-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_diplom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('name',)},
        ),
    ]
